-- begin TAXIMGMT_CUSTOMER_DETAILS
create unique index IDX_TAXIMGMT_CUSTOMER_DETAILS_UNIQ_CUSTOMER_ID on TAXIMGMT_CUSTOMER_DETAILS (CUSTOMER_ID) ^
-- end TAXIMGMT_CUSTOMER_DETAILS

-- begin TAXIMGMT_EMP_CAR_DETAILS
create unique index IDX_TAXIMGMT_EMP_CAR_DETAILS_UNIQ_EMP_CAR_NO on TAXIMGMT_EMP_CAR_DETAILS (EMP_CAR_NO) ^
-- end TAXIMGMT_EMP_CAR_DETAILS
