create unique index IDX_TAXIMGMT_DRIVER_DETAILS_UNIQ_CAR_NUMBER on TAXIMGMT_DRIVER_DETAILS (CAR_NUMBER) ;
create unique index IDX_TAXIMGMT_DRIVER_DETAILS_UNIQ_DRIVER_ID on TAXIMGMT_DRIVER_DETAILS (DRIVER_ID) ;
